# Alembic Configuration

[alembic]
sqlalchemy.url = postgresql+asyncpg://
script_location = alembic
sqlalchemy.echo = false
sqlalchemy.echo_pool = false
version_location_template = %(rel_migrations_path)s/%%(slug)s_%%(rev)s.py
file_template = %%(rev)s_%%(slug)s.py

[loggers]
keys = sqlalchemy.engine, sqlalchemy.pool, alembic
level = WARN

[handlers]
keys = console
level = NOTSET
class = StreamHandler
args = (sys.stderr,)
format = %(levelname)s:%(name)s:%(message)s

[formatters]
keys = generic
format = %(levelname)s:%(name)s:%(message)s
datefmt = %H:%M:%S
